name: ChatMonitor
main: io.github.mooeypoo.chatmonitor.ChatMonitor
version: 1.0.1
description: A plugin that monitors chat and responds to preset list of words.
author: mooeypoo
permissions:
   chatmonitor.words.ignore:
      description: Chat monitor will completely ignore any chat or commands coming from this user.
      default: op
   chatmonitor.cmd.reload:
      description: Allows the user to run the reload command
      default: op
   chatmonitor.cmd.test:
      description: Allows the user to run the test command
      default: op
commands:
   chatmonitor:
      description: Commands triggering actions in ChatMonitor plugin.
      usage: Use `/chatmonitor help` to see the list of all available actions. 
